---
info:
  license:
    name: "MIT"
  title: "Reproducer"
  version: "1.0.0"
openapi: "3.0.0"
paths:
  /upload:
    post:
      operationId: "upload"
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  format: "binary"
                  type: "string"
              type: "object"
            encoding:
              file:
                contentType: "*/*"
        description: "(to be documented)"
      responses:
        "204":
          description: "(to be documented)"
      summary: "upload a file"
